### ISSUE TITLE
Autoplaylists are showing in send selection to.

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Tools-SMP#2]
Hi,

Seeing as it's not possible to send anything to an AP, it would be nice for them to be omitted from this option.

The same goes for the same option in playlist manipulation.

![image](https://user-images.githubusercontent.com/14054664/123175497-c8354e00-d479-11eb-9164-fed113d9ce28.png)

**Comment by regorxxx** [comment]
Yep, forgot it. Was easier than I thought, already done for the next release (considers any locked playlist, not just autoplaylists),

Thanks for the report!

**Comment by stephen147** [comment]
Thanks, looking forward to the fix.
