### ISSUE TITLE
"Similar Tracks" button creates invalid queries

### ISSUE THREAD

**Issue by sundayLOOKplants** [regorxxx/Playlist-Tools-SMP#20]
The Similar Tracks button does not work for me - here's the output from a random The Weeknd track:
```
Query not valid. Check query:
(($ascii(%genre%) IS R&B OR $ascii(%genre%) IS Pop OR $ascii(%genre%) IS Electronic) OR ($ascii(%style%) IS Synthpop OR $ascii(%style%) IS Alternative R&B) OR ("$year(%date%)" GREATER 2005 AND "$year(%date%)" LESS 2035)) AND (NOT (%rating% EQUAL 2 OR %rating% EQUAL 1) AND NOT (STYLE IS Live AND NOT STYLE IS Hi-Fi) AND %channels% LESS 3 AND NOT COMMENT HAS Quad AND TITLE PRESENT AND ARTIST PRESENT AND DATE PRESENT)
```

**Comment by regorxxx** [comment]
There is something wrong there. It should be %style% and not $ascii(%style%), etc. This is obviously fixed on newer versions, but it's possible at some point I released a file with such issue.

1. Which version are you using?
2. By "Similar Tracks" I suppose you are talking about Search by distance buttons, which add 3 buttons (one of them named like that).

I will simply suggest you to delete all files and re-download my scripts again, all of them. Following these instructions:
https://github.com/regorxxx/Playlist-Tools-SMP/wiki/Installation#nightly-versions

Or... open the properties panel and look for :
- To remap genre tag to other tag(s) change this (sep. by comma): $ascii(%genre%)
- To remap style tag to other tag(s) change this (sep. by comma): $ascii('%style%)

Change those to %genre%, %style%, etc. It will fix it.

**Comment by regorxxx** [comment]
Or just download last release and install from zero. :)

**Comment by regorxxx** [comment]
Closing it, let me know if you have any problem.
