### ISSUE TITLE
Property value is wrong

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Tools-SMP#21]
**Describe the bug**
Done a fresh install of SMP and get this error. Using Foobar v2.1 preview build.

```
Property value is wrong. Using default value as fallback:
'Duplicates RegExp title matching?'

Wrong value: true

Replaced with: %RATING%|$ifgreater($strstr($lower(%GENRE%', '%STYLE%', '%FOLKSONOMY%),live),0,0,1)|$ifgreater($if2($strstr($lower(%GENRE%', '%STYLE%', '%FOLKSONOMY%),instrumental),$strstr($lower(%LANGUAGE%),zxx)),0,0,1)

Value obey this condition: function isStringWeak(str){
	return (typeof str === 'string') ? true : false;
}
```
**To Reproduce**
1. Done a fresh install
2. Removed the old toolbar for good measure and loaded the .js file in the root folder xxx-scripts

**Desktop (please complete the following information):**
 - OS: Wind 10 Build 19045

**Additional context**

**Comment by regorxxx** [comment]
Fixed.
