### ISSUE TITLE
[QUESTION] Cannot find playlists from Playlist Manager SMP

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Tools-SMP#22]
The playlist I have in your SMP plugin don't show.

Is this possible to show them? The selection definitely exists in one of the playlists I have. It's a normal playlist.

![image](https://github.com/regorxxx/Playlist-Tools-SMP/assets/14054664/8676d00f-a2da-46d5-acae-6e2193a12281)

**Comment by regorxxx** [comment]
This is not a bug. What you ask is not possible. Playlist Tools is intended to be used on playlist loaded on UI (not on playlist files).

You have multiple tools on Playlist Manager to find if a selected track is on a given playlist file. You can remove the track manually afterwards.

**Comment by stephen147** [comment]
Okay. No worries.
